/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventaris_aset_barang;
import java.sql.SQLException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRDesignViewer;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Herr
 */
public class inventaris_aset extends javax.swing.JFrame {
private Connection con; 
private Statement stat; 
private ResultSet res;
JasperReport JasperReport;
JasperDesign JasperDesign;
JasperPrint JasperPrint;
Map<String,Object> param= new HashMap<String,Object>();



    /**
     * Creates new form inventaris_aset
     */
    public inventaris_aset() {
        initComponents();
        setTitle("Aplikasi Inventaris Aset");
        koneksi();
        tblbarangmasuk1();
        tblbarangkeluar2();
        setLocationRelativeTo(this);
    }
   
private void koneksi()
{ try 
{ 
Class.forName("com.mysql.jdbc.Driver"); con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbinventarisaset", "root", ""); 
stat=con.createStatement(); 
} catch (ClassNotFoundException | SQLException e) { 
JOptionPane.showMessageDialog(null, e); 
} }
    
private void kosongkan()
{ 
txtkodebarang.setText(""); 
txtnamabarang.setText("");
txttanggalmasuk.setText("");
txttanggalkeluar.setText(""); 
txtjumlah.setText("");
comboboxkondisi.setSelectedIndex(-1); 
txtkodebarang.requestFocus();
 }  

    private void comboboxkondisi(){
    comboboxkondisi.addItem("Baik"); 
    comboboxkondisi.addItem("Rusak Ringan");
    comboboxkondisi.addItem("Rusak Berat"); 
    comboboxkondisi.setSelectedIndex(-1); 
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbarangmasuk1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbarangkeluar2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkodebarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txttanggalmasuk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txttanggalkeluar = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        btnbarangmasuk = new javax.swing.JButton();
        btnbarangkeluar = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhapusbarangmasuk = new javax.swing.JButton();
        btnhapusbarangkeluar = new javax.swing.JButton();
        comboboxkondisi = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnubahbarangkeluar = new javax.swing.JButton();
        btncaribarangkeluar = new javax.swing.JButton();
        btncetakbarangmasuk = new javax.swing.JButton();
        btncetakbarangkeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("APLIKASI INVENTARIS ASET");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("DINAS KESEHATAN PROVINSI KALIMANTAN SELATAN");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventaris_aset_gambar/logo_provkalsel.png"))); // NOI18N
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(52, 52, 52))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 1156, 117));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INPUT DATA ASET BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 1156, 48));

        tblbarangmasuk1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tblbarangmasuk1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarangmasuk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangmasuk1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbarangmasuk1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 348, 798, 167));

        tblbarangkeluar2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tblbarangkeluar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarangkeluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangkeluar2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbarangkeluar2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 573, 798, 169));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Kode Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 209, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Nama Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 255, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal Masuk");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 304, -1, -1));

        txtkodebarang.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 206, 201, -1));

        txtnamabarang.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 252, 201, -1));

        txttanggalmasuk.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txttanggalmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 301, 201, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Keluar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 209, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Jumlah");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 255, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Kondisi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 304, -1, -1));

        txttanggalkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txttanggalkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 206, 175, -1));

        txtjumlah.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 252, 175, -1));

        btnbarangmasuk.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnbarangmasuk.setText("Simpan Barang Masuk");
        btnbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangmasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnbarangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 244, 40));

        btnbarangkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnbarangkeluar.setText("Simpan Barang Keluar");
        btnbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbarangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 244, 41));

        btnubah.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnubah.setText("Ubah Tabel Barang Masuk");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 252, 40));

        btnrefresh.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 582, 216, 40));

        btncari.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btncari.setText("Cari Tabel Barang Masuk");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 250, 41));

        btnclear.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 631, 216, 41));

        btnkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 681, 216, 40));

        btnhapusbarangmasuk.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnhapusbarangmasuk.setText("Hapus");
        btnhapusbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusbarangmasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapusbarangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 524, 201, -1));

        btnhapusbarangkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnhapusbarangkeluar.setText("Hapus");
        btnhapusbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusbarangkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapusbarangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 751, 199, 30));

        comboboxkondisi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        comboboxkondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak Ringan", "Rusak Berat" }));
        getContentPane().add(comboboxkondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 301, 175, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("Tabel Data Barang Masuk");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 533, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("Tabel Data Barang Keluar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 753, -1, -1));

        jLabel13.setText("Copyright @Herr | 2023");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 757, -1, -1));

        btnubahbarangkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnubahbarangkeluar.setText("Ubah Tabel Barang Keluar");
        btnubahbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahbarangkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnubahbarangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 466, 252, 40));

        btncaribarangkeluar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btncaribarangkeluar.setText("Cari Tabel Barang Keluar");
        btncaribarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaribarangkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btncaribarangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 515, 252, 41));

        btncetakbarangmasuk.setText("Cetak Barang Masuk");
        btncetakbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakbarangmasukActionPerformed(evt);
            }
        });
        getContentPane().add(btncetakbarangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 524, 200, 31));

        btncetakbarangkeluar.setText("Cetak Barang Keluar");
        btncetakbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakbarangkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btncetakbarangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 751, 201, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventaris_aset_gambar/bg_dinkesprov.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangmasukActionPerformed
        try {
            stat.executeUpdate("insert into inventaris_barang_masuk values ("
                + "'" + txtkodebarang.getText()+"',"
                + "'" + txtnamabarang.getText()+"',"
                + "'" + txttanggalmasuk.getText()+"',"
                + "'" + txtjumlah.getText()+ "',"
                + "'" + comboboxkondisi.getSelectedItem()+ "')");

            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Yang Masukan Tidak Sesuai : "+e);
        }        // TODO add your handling code here:   
    }//GEN-LAST:event_btnbarangmasukActionPerformed

    
    
private void tblbarangmasuk1(){ 
DefaultTableModel t= new DefaultTableModel();
t.addColumn("Kode Barang"); 
t.addColumn("Nama Barang");
t.addColumn("Tanggal Masuk"); 
t.addColumn("Jumlah"); 
t.addColumn("Kondisi"); 
 tblbarangmasuk1.setModel(t); try{ res=stat.executeQuery("select * from inventaris_barang_masuk"); 
 while (res.next()) { 
 t.addRow(new Object[]{ res.getString("Kd_Barang"),
 res.getString("Nama_Barang"), 
 res.getString("Tanggal_Masuk"),  
 res.getString("Jumlah"), 
 res.getString("Kondisi") 
 }); 
 }
 }catch (Exception e) { 
 JOptionPane.showMessageDialog(rootPane, e); 
 }
}

private void tblbarangkeluar2(){ 
DefaultTableModel t= new DefaultTableModel();
t.addColumn("Kode Barang"); 
t.addColumn("Nama Barang");
t.addColumn("Tanggal Masuk");
t.addColumn("Tanggal Keluar"); 
t.addColumn("Jumlah"); 
t.addColumn("Kondisi"); 
 tblbarangkeluar2.setModel(t); try{ res=stat.executeQuery("select * from inventaris_barang_keluar"); 
 while (res.next()) { 
 t.addRow(new Object[]{ res.getString("Kd_Barang"),
 res.getString("Nama_Barang"), 
 res.getString("Tanggal_Masuk"),
 res.getString("Tanggal_Keluar"),
 res.getString("Jumlah"), 
 res.getString("Kondisi") 
 }); 
 }
 }catch (Exception e) { 
 JOptionPane.showMessageDialog(rootPane, e); 
 }
}
    
    
    
    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
    JOptionPane.showMessageDialog(null, "Anda Telah Keluar Dari Aplikasi!!!");
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
        // TODO add your handling code here:
    try {
            res=stat.executeQuery("select * from inventaris_barang_masuk where "+ "kd_barang='" + txtkodebarang.getText()
                +"'" ); while (res.next()) {
                txtnamabarang.setText(res.getString("nama_barang"));
                txttanggalmasuk.setText(res.getString("tanggal_masuk"));
                txtjumlah.setText(res.getString("jumlah"));
                comboboxkondisi.setSelectedItem(res.getString("Kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangActionPerformed

    private void btnbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangkeluarActionPerformed
            try {
            stat.executeUpdate("insert into inventaris_barang_keluar values ("
                + "'" + txtkodebarang.getText()+"',"
                + "'" + txtnamabarang.getText()+"',"
                + "'" + txttanggalmasuk.getText()+"',"
                + "'" + txttanggalkeluar.getText()+"',"        
                + "'" + txtjumlah.getText()+ "',"
                + "'" + comboboxkondisi.getSelectedItem()+ "')");
            
            this.tblbarangmasuk1();
            this.tblbarangkeluar2();
            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Yang Anda Masukan Tidak Sesuai!!! : "+e);
        }        // TODO add your handling code here:  
    }//GEN-LAST:event_btnbarangkeluarActionPerformed

    private void btnhapusbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusbarangmasukActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Anda Yakin Menghapus Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            stat.executeUpdate("delete from inventaris_barang_masuk where "
                + "Kd_Barang='"+txtkodebarang.getText()
                +"'" );

            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Yang Anda Masukan Tidak Sesuai!!! : "+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusbarangmasukActionPerformed

    private void btnhapusbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusbarangkeluarActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Anda Yakin Menghapus Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try {
            stat.executeUpdate("delete from inventaris_barang_keluar where "
                + "Kd_Barang='"+txtkodebarang.getText()
                +"'" );

            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Yang Anda Masukan Tidak Sesuai!!! : "+e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusbarangkeluarActionPerformed

    private void tblbarangmasuk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangmasuk1MouseClicked
        int i = tblbarangmasuk1.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tblbarangmasuk1.getValueAt(i,0);
        String code1 = (String)tblbarangmasuk1.getValueAt(i,1);
        String code2 = (String)tblbarangmasuk1.getValueAt(i,2);
        String code3 = (String)tblbarangmasuk1.getValueAt(i,3);
        String code4 = (String)tblbarangmasuk1.getValueAt(i,4);
        txtkodebarang.setText(code);
        txtnamabarang.setText(code1);
        txttanggalmasuk.setText(code2);
        txtjumlah.setText(code3);
        comboboxkondisi.setSelectedItem(code4);   
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbarangmasuk1MouseClicked

    private void tblbarangkeluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangkeluar2MouseClicked
        int i = tblbarangkeluar2.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tblbarangkeluar2.getValueAt(i,0);
        String code1 = (String)tblbarangkeluar2.getValueAt(i,1);
        String code2 = (String)tblbarangkeluar2.getValueAt(i,2);
        String code3 = (String)tblbarangkeluar2.getValueAt(i,3);
        String code4 = (String)tblbarangkeluar2.getValueAt(i,4);
        String code5 = (String)tblbarangkeluar2.getValueAt(i,5);
        txtkodebarang.setText(code);
        txtnamabarang.setText(code1);
        txttanggalmasuk.setText(code2);
        txttanggalkeluar.setText(code3);
        txtjumlah.setText(code4);
        comboboxkondisi.setSelectedItem(code5); 
        // TODO add your handling code here:
    }//GEN-LAST:event_tblbarangkeluar2MouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        try {
            res=stat.executeQuery("select * from inventaris_barang_masuk where "+ "Kd_Barang='" +txtkodebarang.getText()
                +"'" ); while (res.next()) {
                txtnamabarang.setText(res.getString("Nama_Barang"));
                txttanggalmasuk.setText(res.getString("Tanggal_Masuk"));
                txtjumlah.setText(res.getString("jumlah"));
                comboboxkondisi.setSelectedItem(res.getString("kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Anda Yakin Untuk Merubah Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update inventaris_barang_masuk set kd_barang=?,nama_barang=?,tanggal_masuk=?,jumlah=?,kondisi=? where kd_barang='"+txtkodebarang.getText()+"'";
            
            PreparedStatement st=con.prepareStatement(sql);
            if(ok==0)
            {
                try
                {
                    st.setString(1,txtkodebarang.getText());
                    st.setString(2,txtnamabarang.getText());
                    st.setString(3,txttanggalmasuk.getText());
                    st.setString(4,txtjumlah.getText());
                    st.setString(5,(String)comboboxkondisi.getSelectedItem());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil di Update");
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Data Tidak Berhasil di Update !!!");
                }
            }
        }catch (Exception e){} 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        kosongkan();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
    new inventaris_aset().setVisible(true);
        dispose();
        setLocationRelativeTo(this);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnubahbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahbarangkeluarActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Anda Yakin Untuk Merubah Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update inventaris_barang_keluar set kd_barang=?,nama_barang=?,tanggal_masuk=?,tanggal_keluar=?,jumlah=?,kondisi=? where kd_barang='"+txtkodebarang.getText()+"'";
            
            PreparedStatement st=con.prepareStatement(sql);
            if(ok==0)
            {
                try
                {
                    st.setString(1,txtkodebarang.getText());
                    st.setString(2,txtnamabarang.getText());
                    st.setString(3,txttanggalmasuk.getText());
                    st.setString(4,txttanggalkeluar.getText()); 
                    st.setString(5,txtjumlah.getText());
                    st.setString(6,(String)comboboxkondisi.getSelectedItem());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Berhasil di Update");
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Data Tidak Berhasil di Update !!!");
                }
            }
        }catch (Exception e){}       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnubahbarangkeluarActionPerformed
    
    
    
    private void btncaribarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaribarangkeluarActionPerformed
        try {
            res=stat.executeQuery("select * from inventaris_barang_keluar where "+ "kd_barang='" +txtkodebarang.getText()
                +"'" ); while (res.next()) {
                txtnamabarang.setText(res.getString("nama_barang"));
                txttanggalmasuk.setText(res.getString("tanggal_masuk"));
                txttanggalkeluar.setText(res.getString("tanggal_keluar"));
                txtjumlah.setText(res.getString("jumlah"));
                comboboxkondisi.setSelectedItem(res.getString("kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btncaribarangkeluarActionPerformed

    private void btncetakbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakbarangmasukActionPerformed
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///dbinventarisaset", "root", "");
            File file = new File("src/inventaris_aset_barang/report_barangmasuk.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Data Tidak Dapat di cetak !!!"+"\n"+ e.getMessage(), "Cetak Dataa",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btncetakbarangmasukActionPerformed

    private void btncetakbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakbarangkeluarActionPerformed
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///dbinventarisaset", "root", "");
            File file = new File("src/inventaris_aset_barang/report_barangkeluar.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Data Tidak Dapat di cetak !!!"+"\n"+ e.getMessage(), "Cetak Dataa",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btncetakbarangkeluarActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventaris_aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventaris_aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventaris_aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventaris_aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventaris_aset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbarangkeluar;
    private javax.swing.JButton btnbarangmasuk;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncaribarangkeluar;
    private javax.swing.JButton btncetakbarangkeluar;
    private javax.swing.JButton btncetakbarangmasuk;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhapusbarangkeluar;
    private javax.swing.JButton btnhapusbarangmasuk;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton btnubahbarangkeluar;
    private javax.swing.JComboBox<String> comboboxkondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblbarangkeluar2;
    private javax.swing.JTable tblbarangmasuk1;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txttanggalkeluar;
    private javax.swing.JTextField txttanggalmasuk;
    // End of variables declaration//GEN-END:variables
}
